name: Selenium UI Tests with Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      selenium:
        image: selenium/standalone-chrome:latest
        options: --shm-size=2g

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          sudo apt-get install -y chromium-browser chromium-chromedriver
          pip install -r requirements.txt

      - name: Lint with flake8
        run: flake8 .

      - name: Check code formatting with black
        run: black --check .

      - name: Run tests
        run: pytest

